name: Bug Report
description: If something isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Make sure that you are submitting a new bug that was not previously reported or already fixed.

        Please use a concise and distinct title for the issue.

        If possible, attach screenshots, videos or links to posts to illustrate the problem.
  - type: textarea
    attributes:
      label: Detailed description
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
      description: What were you trying to do?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Debug information
      description: |
        This info can be copied from the 'About' screen in Tusky 24+.
        If you are on a lower version or can't access the screen, please provide us with the Tusky Version, Android Version, Device and the Mastodon instance this problem occurred on.
      placeholder: |
        Tusky Test 22.0-b814c2c0
        Android 12
        Fairphone 4
        mastodon.social
    validations:
      required: true
